//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arackiralama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accounts()
        {
            this.Contacts = new HashSet<Contacts>();
        }
    
        public int ID { get; set; }
        public int RoleID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> HitAt { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string GovermentNo { get; set; }
        public string Phone { get; set; }
        public string CellPhone { get; set; }
        public string Address { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> PartnerID { get; set; }
        public string ZipCode { get; set; }
        public string CityName { get; set; }
        public string RegionName { get; set; }
        public string FaxNumber { get; set; }
        public string UniqueKey { get; set; }
        public short Status { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public string AvatarResim { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> DateOfRegistration { get; set; }
        public Nullable<System.DateTime> DateOfUpdate { get; set; }
        public string RecordPerson { get; set; }
        public string UpdatedPerson { get; set; }
        public string PasswordAgain { get; set; }
        public Nullable<bool> CookiePolicyIsChecked { get; set; }
        public bool FirstLoggin { get; set; }
        public bool FirstLoginChecked { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contacts> Contacts { get; set; }
        public IEnumerable<Rol> Rol { get; set; }
    }
}
