//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arackiralama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int ID { get; set; }
        public Nullable<int> CultureID { get; set; }
        public string Title { get; set; }
        public string ImageURL { get; set; }
        public string ShowCaseDescription { get; set; }
        public string DescriptionCK { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public string IsActive { get; set; }
        public string ImageTitle { get; set; }
        public IEnumerable<Cultures> cultureList { get; set; }
        public virtual Cultures Cultures { get; set; }
        public virtual Language Language { get; set; }
    }
}
