//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arackiralama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.CarLocation = new HashSet<CarLocation>();
            this.OrderHistory = new HashSet<OrderHistory>();
            this.OrderHistoryDetail = new HashSet<OrderHistoryDetail>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string Sinif { get; set; }
        public string Segment { get; set; }
        public string Resim { get; set; }
        public string KisiSayisi { get; set; }
        public string BagajKapasitesi { get; set; }
        public string KapiSaysi { get; set; }
        public string Sanzuman { get; set; }
        public string YakitTuru { get; set; }
        public Nullable<int> CarPoitScaleID { get; set; }
        public Nullable<int> CarExtraMaterialID { get; set; }
        public Nullable<double> KiralamaTutari { get; set; }
        public Nullable<System.DateTime> EklendigiTarih { get; set; }
        public string EkleyenKisi { get; set; }
        public Nullable<System.DateTime> GuncellendigiTarih { get; set; }
        public string GuncelleyenKisi { get; set; }
        public string IsActive { get; set; }
    
        public virtual CarPointScale CarPointScale { get; set; }
        public virtual Company Company { get; set; }
        public virtual ExtraMaterial ExtraMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarLocation> CarLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderHistory> OrderHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderHistoryDetail> OrderHistoryDetail { get; set; }
    }
}
