//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arackiralama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarLocation()
        {
            this.OrderHistory = new HashSet<OrderHistory>();
            this.OrderHistoryDetail = new HashSet<OrderHistoryDetail>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> CarID { get; set; }
        public Nullable<System.Guid> MemberID { get; set; }
        public string KiralandigiYer { get; set; }
        public Nullable<System.DateTime> KiralandigiTarih { get; set; }
        public string KiralandigiSaat { get; set; }
        public string TeslimEdildigiYer { get; set; }
        public Nullable<System.DateTime> TeslimEdildigiTarih { get; set; }
        public string TeslimEdildigiSaat { get; set; }
        public Nullable<int> KiralandigiTutar { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderHistory> OrderHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderHistoryDetail> OrderHistoryDetail { get; set; }
    }
}
