//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arackiralama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Car = new HashSet<Car>();
            this.OrderHistory = new HashSet<OrderHistory>();
            this.OrderHistoryDetail = new HashSet<OrderHistoryDetail>();
        }
    
        public int ID { get; set; }
        public string Logo { get; set; }
        public string SirketAdi { get; set; }
        public string TicariUnvani { get; set; }
        public string VergiDairesi { get; set; }
        public string VergiNo { get; set; }
        public string SirketTuru { get; set; }
        public string SirketSahibi { get; set; }
        public Nullable<System.DateTime> EklendigiTarih { get; set; }
        public string EkleyenKisi { get; set; }
        public Nullable<System.DateTime> GuncellendigiTarih { get; set; }
        public string GuncelleyenKisi { get; set; }
        public string IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Car> Car { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderHistory> OrderHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderHistoryDetail> OrderHistoryDetail { get; set; }
    }
}
