//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arackiralama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInfoTranslation
    {
        public int ID { get; set; }
        public Nullable<int> CultureID { get; set; }
        public Nullable<int> ContactInfoID { get; set; }
        public string Title { get; set; }
        public string Explanation { get; set; }
        public string IsActive { get; set; }
        public IEnumerable<Cultures> cultureList { get; set; }
        public virtual ContactInfo ContactInfo { get; set; }
        public virtual Cultures Cultures { get; set; }
        public virtual Language Language { get; set; }
    }
}
