//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arackiralama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtraMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExtraMaterial()
        {
            this.Car = new HashSet<Car>();
        }
    
        public int ID { get; set; }
        public string Icon { get; set; }
        public string Materyal { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> MinDeger { get; set; }
        public Nullable<int> MaxDeger { get; set; }
        public Nullable<System.DateTime> EklendigiTarih { get; set; }
        public string EkleyenKisi { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
        public string GuncelleyenKisi { get; set; }
        public string IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Car> Car { get; set; }
    }
}
