//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arackiralama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQTranslation
    {
        public int ID { get; set; }
        public Nullable<int> CultureID { get; set; }
        public Nullable<int> FAQID { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public string IsActiive { get; set; }
        public IEnumerable<Cultures> cultureList { get; set; }
        public virtual Cultures Cultures { get; set; }
        public virtual FAQ FAQ { get; set; }
        public virtual Language Language { get; set; }
    }
}
