//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arackiralama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionTranslations
    {
        public int ID { get; set; }
        public int RegionID { get; set; }
        public int CultureID { get; set; }
        public string Name { get; set; }
        public string Slug { get; set; }
    
        public virtual Cultures Cultures { get; set; }
        public virtual Regions Regions { get; set; }
    }
}
