//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arackiralama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.CarLocation = new HashSet<CarLocation>();
            this.OrderHistory = new HashSet<OrderHistory>();
            this.OrderHistoryDetail = new HashSet<OrderHistoryDetail>();
        }
    
        public System.Guid ID { get; set; }
        public string AvatarResim { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Telefon { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string Adres { get; set; }
        public string EPosta { get; set; }
        public string Sifre { get; set; }
        public string SifreTekrar { get; set; }
        public string Cinsiyet { get; set; }
        public Nullable<System.DateTime> SonGirisTarihi { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public string KayıtEdenKisi { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
        public string GuncelleyenKisi { get; set; }
        public Nullable<int> RolID { get; set; }
        public string IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarLocation> CarLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderHistory> OrderHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderHistoryDetail> OrderHistoryDetail { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
