//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arackiralama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleInfo
    {
        public int ID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string GearType { get; set; }
        public string PassengerCount { get; set; }
        public string FuelType { get; set; }
        public string DoorCount { get; set; }
        public string BaggageCount { get; set; }
        public string CompanyImage { get; set; }
        public Nullable<int> VehicleOrdersID { get; set; }
        public string CompanyName { get; set; }
        public string ThumImage { get; set; }
        public string OfficeName { get; set; }
        public string OfficeAddress { get; set; }
        public string OfficeTel { get; set; }
        public string FuelPolicy { get; set; }
        public string Name { get; set; }
        public Nullable<bool> AirConditionInd { get; set; }
        public string TransmissionType { get; set; }
        public string VehicleCharges { get; set; }
        public string PricedCoverages { get; set; }
    
        public virtual VehicleOrders VehicleOrders { get; set; }
    }
}
